sudo: required
services:
  - docker
script: docker build -t vertcoind . && ( docker run vertcoind -version | tee /dev/stderr | grep -q $(cat VERSION) ) 2>&1
notifications:
  email:
    on_success: never
